=== TheLazySquid/DiscordCssSnippets/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://thelazysquid.github.io/DiscordCssSnippets/snippet.schema.json",
    "title": "Snippet",
    "description": "A CSS snippet for discord",
    "type": "object",
    "required": ["author", "description", "category"],
    "properties": {
        "author": {
            "type": "string",
            "description": "The author of the snippet"
        },
        "description": {
            "type": ["array", "string"],
            "items": {
                "type": "string"
            },
            "description": "A description of the snippet"
        },
        "category": {
            "type": "string",
            "description": "The category of the snippet"
        },
        "preview": {
            "type": "string",
            "description": "The relative file name of a preview image/video for a snippet"
        }
    }
}

=== TheLazySquid/DiscordCssSnippets/snippets/TwoRowChatBar/meta.json
{
    "author": "dav",
    "description": [
        "For those who may want the two-row chat bar layout in the event the visual refresh exp. gets removed.",
        "Accessory bar height adjusts based on UI Density option.",
        "Gif and Sticker buttons do not appear in the HTML with this snippet on."
    ],
    "category": "Improvement",
    "preview": "preview.png"
}

=== TheLazySquid/DiscordCssSnippets/snippets/PageSwapperRefresh/meta.json
{
    "author": "dav",
    "description": [
        "Small redesign to the page swapper in search results",
        "New button design following the mana design style",
        "Now always visible at the bottom of the screen instead of having to scroll",
        "Aligned with user panels and chat bar at the bottom of the screen"
    ],
    "category": "Improvement",
    "preview": "preview.png"
}
